project:
  type: website

website:
  google-analytics: "G-YWJHMVKG1Q"
  page-footer:
    left: Blog realizado con [Quarto](https://quarto.org/), por LMRV.
    right:
      - icon: github
        href: https://github.com/riveravela
      - icon: twitter
        href: https://twitter.com/riveravela
  title: "riveravela"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/riveravela
      - icon: twitter
        href: https://twitter.com/riveravela
  cookie-consent: true
format:
  html:
    theme: flatly
    css: styles.css
    link-external-icon: true
    toc: true

editor: visual

format:
  html:
    include-in-header:
    <script type="text/plain" cookie-consent="targeting" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9751378391732448"
     crossorigin="anonymous" >
</script>