project:
  type: website

website:
  title: "riveravela"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/riveravela
      - icon: twitter
        href: https://twitter.com/riveravela
format:
  html:
    theme: slate
    css: styles.css

editor: visual

