project:
  type: website

website:
  page-footer:
    left: Blog realizado con [Quarto](https://quarto.org/), por LMRV.
    right:
      - icon: github
        href: https://github.com/riveravela
      - icon: twitter
        href: https://twitter.com/riveravela
  title: "riveravela"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/riveravela
      - icon: twitter
        href: https://twitter.com/riveravela
format:
  html:
    theme: slate
    css: styles.css
    link-external-icon: true
    toc: true

editor: visual

